// Code generated by protoc-gen-go. DO NOT EDIT.
// source: golangBowlingAPI.proto

/*
Package golangBowlingAPI is a generated protocol buffer package.

It is generated from these files:
	golangBowlingAPI.proto

It has these top-level messages:
	Throw
	Score
*/
package golangBowlingAPI

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Throw struct {
	Score int32 `protobuf:"varint,1,opt,name=score" json:"score,omitempty"`
}

func (m *Throw) Reset()                    { *m = Throw{} }
func (m *Throw) String() string            { return proto.CompactTextString(m) }
func (*Throw) ProtoMessage()               {}
func (*Throw) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Throw) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

type Score struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *Score) Reset()                    { *m = Score{} }
func (m *Score) String() string            { return proto.CompactTextString(m) }
func (*Score) ProtoMessage()               {}
func (*Score) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Score) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Throw)(nil), "Throw")
	proto.RegisterType((*Score)(nil), "Score")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BowlingService service

type BowlingServiceClient interface {
	Bowl(ctx context.Context, in *Throw, opts ...grpc.CallOption) (*Score, error)
}

type bowlingServiceClient struct {
	cc *grpc.ClientConn
}

func NewBowlingServiceClient(cc *grpc.ClientConn) BowlingServiceClient {
	return &bowlingServiceClient{cc}
}

func (c *bowlingServiceClient) Bowl(ctx context.Context, in *Throw, opts ...grpc.CallOption) (*Score, error) {
	out := new(Score)
	err := grpc.Invoke(ctx, "/BowlingService/Bowl", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BowlingService service

type BowlingServiceServer interface {
	Bowl(context.Context, *Throw) (*Score, error)
}

func RegisterBowlingServiceServer(s *grpc.Server, srv BowlingServiceServer) {
	s.RegisterService(&_BowlingService_serviceDesc, srv)
}

func _BowlingService_Bowl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Throw)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BowlingServiceServer).Bowl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BowlingService/Bowl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BowlingServiceServer).Bowl(ctx, req.(*Throw))
	}
	return interceptor(ctx, in, info, handler)
}

var _BowlingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BowlingService",
	HandlerType: (*BowlingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bowl",
			Handler:    _BowlingService_Bowl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "golangBowlingAPI.proto",
}

func init() { proto.RegisterFile("golangBowlingAPI.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0xcf, 0xcf, 0x49,
	0xcc, 0x4b, 0x77, 0xca, 0x2f, 0xcf, 0xc9, 0xcc, 0x4b, 0x77, 0x0c, 0xf0, 0xd4, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x57, 0x92, 0xe5, 0x62, 0x0d, 0xc9, 0x28, 0xca, 0x2f, 0x17, 0x12, 0xe1, 0x62, 0x2d,
	0x4e, 0xce, 0x2f, 0x4a, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0x70, 0x94, 0xe4, 0xb9,
	0x58, 0x83, 0x41, 0x0c, 0x21, 0x31, 0x2e, 0xb6, 0xa2, 0xd4, 0xe2, 0xd2, 0x9c, 0x12, 0xa8, 0x3c,
	0x94, 0x67, 0xa4, 0xc5, 0xc5, 0x07, 0x35, 0x33, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0x48,
	0x82, 0x8b, 0x05, 0x24, 0x22, 0xc4, 0xa6, 0x07, 0x36, 0x58, 0x8a, 0x4d, 0x0f, 0x6c, 0x82, 0x12,
	0x43, 0x12, 0x1b, 0xd8, 0x4a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xad, 0x29, 0x9a, 0xa7,
	0x8c, 0x00, 0x00, 0x00,
}
